function h=customPlot(XData,YData,stepSize,lineColor,...
                    lineStyle,markerColor,markerStyle,lineWidth)
%% Info:
% This function was developed with the aim of increasing clarity of figures
% when markers are used. since MATLAB puts a marker for every single data
% point on figures, for large data, this may increase the size of
% vectorized figure as well as its clarity. Hence, a new variable named
% 'stepSize' was introduced in order to distribute markers over figures in
% a user-defined fashion.


% Written by: A. H. Namadchi (10/2017)
%% Core
hold on
plot(XData,YData,...
    'LineStyle',lineStyle,...
    'Marker','none',...
    'Color',lineColor,...
    'LineWidth',lineWidth);

plot(XData(1:stepSize:end),...
     YData(1:stepSize:end),...
     'Color',lineColor,...
     'LineStyle','none',...
     'Marker',markerStyle,...
     'MarkerFaceColor',markerColor);
 
h=plot(NaN,NaN,...
    'LineStyle',lineStyle,...
    'Marker',markerStyle,...
    'Color',lineColor,...
    'MarkerFaceColor',markerColor,...
    'LineWidth',lineWidth);



end